services:

  blazorapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=stocktrackerDB;Username=root;Password=root
    volumes:
      - .:/app
      - /app/obj
      - /app/bin
    depends_on:
      - postgres_db

  postgres_db:
      image: postgres:latest
      environment:
        POSTGRES_DB: stocktrackerDB
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: